#!/usr/bin/env python3
"""The catalog of what draws UZE's icons correctly, generated from evidence.

    catalog.py write EVIDENCE_DIR     # a Lab run's verdict.json, plus evidence/manual/*.json
    catalog.py compare EVIDENCE_DIR   # does a fresh run still say what the catalog says?
    catalog.py docs [--check]         # the appearance page's catalog, from evidence/catalog.json

`write` summarises a run into the committed `evidence/catalog.json`.
`docs` renders that summary into the region between the catalog markers of
the appearance page. `--check` fails when the page says something the
evidence does not, which `ci.yml` runs. Standard library only, so the check
needs no image.
"""

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CATALOG = HERE / "evidence" / "catalog.json"
MANUAL = HERE / "evidence" / "manual"
PAGES = [ROOT / "web" / "content" / "docs" / "appearance.mdx"]
BEGIN = (
    "{/* rendering-catalog:begin — generated by conformance/rendering/catalog.py */}"
)
END = "{/* rendering-catalog:end */}"
BUILDS = ["plain", "mono", "propo"]


def summarise(results: list[dict], manual: bool) -> dict:
    terminals: dict[str, dict] = {}
    for result in results:
        name = result["terminal"]
        entry = terminals.setdefault(
            name,
            {"version": result.get("terminal_version"), "manual": manual, "cases": []},
        )
        if result.get("unsupported"):
            entry["unsupported"] = result["unsupported"]
            continue
        failing = {k: v for k, v in result.get("criteria", {}).items() if v}
        entry["cases"].append(
            {
                "family": result.get("family") or result.get("font"),
                "build": result.get("build", "unknown"),
                "passes": bool(result.get("passes")),
                "icon_size": result.get("icon_size"),
                "spread": result.get("spread"),
                "failing": failing
                or ({"drawn": [result["error"]]} if result.get("error") else {}),
            }
        )
    for entry in terminals.values():
        entry["cases"].sort(
            key=lambda c: (
                c["family"],
                BUILDS.index(c["build"]) if c["build"] in BUILDS else 9,
            )
        )
    return terminals


def from_run(evidence: Path) -> dict:
    run = json.loads((evidence / "verdict.json").read_text())
    terminals = summarise(run["results"], manual=False)
    for path in sorted(MANUAL.glob("*.json")):
        verdict = json.loads(path.read_text())
        terminals.update(summarise([verdict], manual=True))
    return {"set": run["set"], "terminals": terminals}


def write(evidence: Path) -> int:
    CATALOG.write_text(json.dumps(from_run(evidence), indent=2, sort_keys=True) + "\n")
    print(f"wrote {CATALOG.relative_to(ROOT)}")
    return 0


def verdicts(catalog: dict) -> dict:
    """What a reader is told: which cases pass, and on which criterion the
    others fail. Sizes are measurements, not claims, so a pixel of
    difference between two runs is not a disagreement."""
    return {
        name: entry.get("unsupported")
        or [
            (c["family"], c["build"], c["passes"], sorted(c["failing"]))
            for c in entry["cases"]
        ]
        for name, entry in catalog["terminals"].items()
    }


def compare(evidence: Path) -> int:
    fresh, committed = (
        verdicts(from_run(evidence)),
        verdicts(json.loads(CATALOG.read_text())),
    )
    if fresh == committed:
        print("the fresh run agrees with evidence/catalog.json")
        return 0
    for name in sorted(set(fresh) | set(committed)):
        if fresh.get(name) != committed.get(name):
            print(
                f"{name}: committed {committed.get(name)}\n{' ' * len(name)}  fresh     {fresh.get(name)}"
            )
    print(
        "a regression, or a catalog to update with `catalog.py write` and `catalog.py docs`",
        file=sys.stderr,
    )
    return 1


def short_version(reported: str) -> str:
    """The version number out of whatever `--version` printed: `foot version:
    1.21.0 +pgo +ime` and `kitty 0.41.1 created by …` both come down to it."""
    match = re.search(r"\d+\.\d+(?:[.\-]\w+)*|\d{3,}", reported)
    return match.group(0) if match else reported.replace("|", "/")


def verdict_cell(cases: list[dict]) -> str:
    """How many fonts of this build pass, and the size icons come out at:
    the median over the families, in cell heights."""
    if not cases:
        return "—"
    passing = sum(case["passes"] for case in cases)
    mark = "✓" if passing == len(cases) else "✗"
    sizes = sorted(c["icon_size"] for c in cases if c.get("icon_size"))
    size = f" · {sizes[len(sizes) // 2]:.2f}" if sizes else ""
    return f"{mark} {passing}/{len(cases)}{size}"


def table(catalog: dict) -> str:
    lines = [
        "| Terminal | Version | Plain | Mono | Propo | Evidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    notes = []
    for name, entry in sorted(catalog["terminals"].items()):
        if entry.get("unsupported"):
            lines.append(
                f"| {name} | — | — | — | — | not verified: {entry['unsupported']} |"
            )
            continue
        by_build = {b: [c for c in entry["cases"] if c["build"] == b] for b in BUILDS}
        evidence = "manual screenshot" if entry["manual"] else "Rendering Lab"
        version = short_version(entry.get("version") or "")
        lines.append(
            f"| {name} | {version} | "
            + " | ".join(verdict_cell(by_build[b]) for b in BUILDS)
            + f" | {evidence} |"
        )
        for case in entry["cases"]:
            if not case["passes"]:
                criteria = ", ".join(sorted(case["failing"])) or "failed"
                notes.append(
                    f"- **{name}**, {case['family']} {case['build']}: {criteria}"
                )
    text = "\n".join(lines) + "\n"
    if notes:
        text += (
            "\nWhere a case fails, and on which criterion:\n\n"
            + "\n".join(notes)
            + "\n"
        )
    return text


def render_into(page: Path, body: str) -> str:
    text = page.read_text()
    if BEGIN not in text or END not in text:
        raise SystemExit(f"{page.relative_to(ROOT)} has no catalog markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n\n{body}\n{END}{tail}"


def docs(check: bool) -> int:
    catalog = json.loads(CATALOG.read_text())
    body = table(catalog)
    stale = []
    for page in PAGES:
        rendered = render_into(page, body)
        if rendered != page.read_text():
            if check:
                stale.append(str(page.relative_to(ROOT)))
            else:
                page.write_text(rendered)
                print(f"updated {page.relative_to(ROOT)}")
    if stale:
        print(
            "the rendering catalog on these pages differs from evidence/catalog.json — "
            f"run `python3 conformance/rendering/catalog.py docs`: {', '.join(stale)}",
            file=sys.stderr,
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    write_cmd = sub.add_parser("write")
    write_cmd.add_argument("evidence", type=Path)
    compare_cmd = sub.add_parser("compare")
    compare_cmd.add_argument("evidence", type=Path)
    docs_cmd = sub.add_parser("docs")
    docs_cmd.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.command == "write":
        return write(args.evidence)
    if args.command == "compare":
        return compare(args.evidence)
    return docs(args.check)


if __name__ == "__main__":
    sys.exit(main())
