#!/usr/bin/env python3
"""Generates `crates/uze-theme/themes/nerd.json`, choosing each icon by
meaning first and then by measurement.

Every symbol lists the icon names that would say the right thing, most
fitting first. The generator keeps the first candidate whose size, in every
build of every font in the catalog, lies within the tolerance of the set's
median in that font. The reason is not taste:

- A **Mono** build shrinks an icon until it fits one cell's width, so a wide
  icon comes out short.
- A **plain** build sizes icons by source family and lets them run into the
  next cell.

An icon that is one size under both rules is close to square and fills its
own box, and that is what the candidates are ordered to find. The Codicons
that fill their box measure alike in both builds, so they come first, and
another family is a fallback where Codicons has nothing that says it.

Codepoints are resolved from the pinned `glyphnames.json` by name, never
typed.

**Marks** are exempt from *One size*, each with its reason. These are the
glyphs drawn at text weight by meaning: a bullet, a caret, an arrow beside a
number. Held to the band, they would have to be drawn as pictograms, which
is the wrong answer to "a small thing sits here". They are still held to
*Contained*.

`python3 conformance/rendering/generate_nerd.py [--check]`
"""

import argparse
import json
import sys
from pathlib import Path
from statistics import median

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import fonts as catalog  # noqa: E402
import metrics  # noqa: E402
from nerd_set import ICONS, LAB_REJECTED, MARKS  # noqa: E402

import contract  # noqa: E402

TARGET = HERE.parent.parent / "crates" / "uze-theme" / "themes" / "nerd.json"

DESCRIPTION = (
    "UZE's marks drawn from a patched icon font. Needs Nerd Fonts v3 or newer, "
    "in any build: plain, Mono or Propo. Generated by "
    "conformance/rendering/generate_nerd.py from the official glyphnames.json by "
    "name, never by codepoint. Each icon is chosen by meaning first and then by "
    "measurement, so every icon is one optical size in every build of every font "
    "in the Lab's catalog. Every build reserves one cell for an icon, which is "
    "the width declared here; UZE draws a blank cell after each icon so that a "
    "build or terminal drawing it wider has room. Declares only the marks an "
    "icon says better than a letterform: box drawing, bars and typography are "
    "the built-in default's, which any patched font draws."
)

ROUNDS = 8


def is_mark(symbol: str) -> bool:
    return symbol in MARKS


def _sizes(readers, glyph: str) -> list[float | None]:
    sizes = []
    for reader in readers:
        measured = reader.measure(glyph)
        sizes.append(
            None
            if measured is None
            else contract.optical_size(measured.ink, reader.cell_aspect)
        )
    return sizes


def choose(names: dict, readers) -> tuple[dict[str, str], list[float]]:
    """The first candidate per icon that sits within the tolerance of the
    set's median in every font, iterated until the medians settle."""
    measured = {
        symbol: {name: _sizes(readers, names[name]["char"]) for name in candidates}
        for symbol, candidates in ICONS.items()
    }
    chosen = {symbol: candidates[0] for symbol, candidates in ICONS.items()}
    medians: list[float] = []
    for _ in range(ROUNDS):
        medians = []
        for index in range(len(readers)):
            sizes = [
                measured[s][chosen[s]][index]
                for s in ICONS
                if not is_mark(s) and measured[s][chosen[s]][index] is not None
            ]
            medians.append(median(sizes))
        settled = dict(chosen)
        for symbol, candidates in ICONS.items():
            if is_mark(symbol):
                continue
            for name in candidates:
                if name in LAB_REJECTED.get(symbol, {}):
                    continue
                sizes = measured[symbol][name]
                if all(
                    size is not None and abs(size / middle - 1) <= contract.TOLERANCE
                    for size, middle in zip(sizes, medians)
                ):
                    settled[symbol] = name
                    break
        if settled == chosen:
            break
        chosen = settled
    return chosen, medians


def render(names: dict, chosen: dict[str, str]) -> str:
    symbols = {
        symbol: {"glyph": names[name]["char"], "width": 1}
        for symbol, name in chosen.items()
    }
    document = {
        "version": 1,
        "name": "uze nerd",
        "description": DESCRIPTION,
        "symbols": symbols,
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if nerd.json would change"
    )
    parser.add_argument(
        "--target", type=Path, default=TARGET, help="the nerd.json to write or check"
    )
    args = parser.parse_args()
    names = catalog.glyphnames()
    unknown = [n for c in ICONS.values() for n in c if n not in names]
    if unknown:
        raise SystemExit(f"not in the pinned glyphnames.json: {', '.join(unknown)}")
    installed = catalog.installed()
    readers = [metrics.FontReader(font.path) for font in installed]
    chosen, medians = choose(names, readers)
    text = render(names, chosen)
    for symbol, name in chosen.items():
        note = f"  (mark: {MARKS[symbol]})" if is_mark(symbol) else ""
        print(f"{symbol:22} {name}{note}")
    if args.check:
        if args.target.read_text() != text:
            print("nerd.json differs from what the generator produces", file=sys.stderr)
            return 1
        return 0
    args.target.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
